---
title: "MD GROMACS RMarkdown"
author: "Dr Praveen Kumar-M"
date: "09/10/2020"
output: html_document
---

Notes for Git
git rm . -r  --cached for removing the cache from staging

  #Make a directory for working of molecular dynamics

```{bash}
mkdir /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245

```

[https://www.tecmint.com/linux-find-command-to-search-multiple-filenames-extensions/]
1. Assuming that you want to find all files in the current directory with .sh and .txt file extensions, you can do this by running the command below:

find . -type f \( -name "*.sh" -o -name "*.txt" \)
Find .sh and .txt Extension Files in Linux
Find .sh and .txt Extension Files in Linux
Interpretation of the command above:

. means the current directory
-type option is used to specify file type and here, we are searching for regular files as represented by f
-name option is used to specify a search pattern in this case, the file extensions
-o means “OR”
It is recommended that you enclose the file extensions in a bracket, and also use the \ ( back slash) escape character as in the command.



find /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files -type f \(-name "6TOU_clean.pdb" -o -name "em.mdp" -o -name "ions.mdp" -o -name "md.mdp" -o -name "npt.mdp" -o -name "nvt.mdp" \) -exec cp {} \;


#Transferring of files mdp, pdb, ligand and force field to the working directory
List of mdp files to be transferred as 
em.mdp 
ions.mdp
md.mdp
npt.mdp
nvt.mdp

The files mdout.mdp is the output mdp and it is not requried to be transferred. 
```{bash}
find /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files -type f -name *.mdp -exec cp {} /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245 \;
find /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files -type f -name *.pdb -exec cp {} /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245 \;
find /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_top_100_Files -type f -name *39_33245* -exec cp {} /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245 \;
find /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/charmm36-mar2019.ff -exec cp {} /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245 -r \;
```
<!-- output -->
<!-- cp /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/nvt.mdp /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/em.mdp -->
<!-- /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/ions.mdp -->
<!-- /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/md.mdp -->
<!-- /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/npt.mdp -->
<!-- /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/6TOU_clean.pdb -->
<!-- /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245 -->





cp /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/nvt.mdp /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/em.mdp
/home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/ions.mdp
/home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/md.mdp
/home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/npt.mdp
/home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/Repository_of_Files/6TOU_clean.pdb
/home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245

#Energy minized/ Docked/ Save the docked ligand relative to protein as a mol2 file
```{bash}
cd ~/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
chimera 6TOU_clean.pdb MD_ligand39_33245.mol2

```
Tools --> Structure editing --> Minimize structure --> Select only the ligand --> Click OK for all (AMBER is the default right force field) 

Tools --> Structure/Binding analysis --> Autodock Vina --> give name to output as ("manualdock") and select the appropriate ligand in the ligand selection


#
Then enter the center and box size in the appropriate field (You will get this information from conf file)

Save mol2
Only select the docked model (that is 1)
The click save relative to protein
Enter the ZINC name fully removing the 0000

Save pdb
Only select the docked model (that is 1)
The click save relative to protein
Enter the ZINC name fully removing the 0000


#Addition of hydrogen to the mol2 file
```{bash}
avagadro2 ZINC22483429.mol2
```

Build --> Hydrogen --> add hydrogen
Selected Molecule in the top ribbon --> selected the file pattern as Sylbyl mol2 --> Entered the file as as ZINC***_H.mol2

#Generation of topology file of ligand in swissparam.ch
Utilization of http://www.swissparam.ch/submit.php to generate the topology file of ligand

```{bash}
mv /home/praveenkumarpgiindia/Downloads/ZINC22483429_H.zip /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
```


```{bash}
unzip /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245/ZINC22483429_H.zip
```

#pdb2gmx creation of protein gro
```{bash}
gmx pdb2gmx -f 6TOU_clean.pdb -ignh 

```

GROMACS:      gmx pdb2gmx, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx pdb2gmx -f 6TOU_clean.pdb -ignh


Select the Force Field:
From current directory:
 1: CHARMM36 all-atom force field (March 2019)
From '/home/praveenkumarpgiindia/gromacs-2020.1/share/top':
 2: AMBER03 protein, nucleic AMBER94 (Duan et al., J. Comp. Chem. 24, 1999-2012, 2003)
 3: AMBER94 force field (Cornell et al., JACS 117, 5179-5197, 1995)
 4: AMBER96 protein, nucleic AMBER94 (Kollman et al., Acc. Chem. Res. 29, 461-469, 1996)
 5: AMBER99 protein, nucleic AMBER94 (Wang et al., J. Comp. Chem. 21, 1049-1074, 2000)
 6: AMBER99SB protein, nucleic AMBER94 (Hornak et al., Proteins 65, 712-725, 2006)
 7: AMBER99SB-ILDN protein, nucleic AMBER94 (Lindorff-Larsen et al., Proteins 78, 1950-58, 2010)
 8: AMBERGS force field (Garcia & Sanbonmatsu, PNAS 99, 2782-2787, 2002)
 9: CHARMM27 all-atom force field (CHARM22 plus CMAP for proteins)
10: GROMOS96 43a1 force field
11: GROMOS96 43a2 force field (improved alkane dihedrals)
12: GROMOS96 45a3 force field (Schuler JCC 2001 22 1205)
13: GROMOS96 53a5 force field (JCC 2004 vol 25 pag 1656)
14: GROMOS96 53a6 force field (JCC 2004 vol 25 pag 1656)
15: GROMOS96 54a7 force field (Eur. Biophys. J. (2011), 40,, 843-856, DOI: 10.1007/s00249-011-0700-9)
16: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
1

Using the Charmm36-mar2019 force field in directory ./charmm36-mar2019.ff

Opening force field file ./charmm36-mar2019.ff/watermodels.dat

Select the Water Model:
 1: TIP3P       TIP 3-point, recommended, by default uses CHARMM TIP3 with LJ on H
 2: TIP4P       TIP 4-point
 3: TIP5P       TIP 5-point
 4: SPC         simple point charge
 5: SPC/E       extended simple point charge
 6: None
1
going to rename ./charmm36-mar2019.ff/merged.r2b
Opening force field file ./charmm36-mar2019.ff/merged.r2b
Reading 6TOU_clean.pdb...
Read '', 547 atoms
Analyzing pdb file
Splitting chemical chains based on TER records or chain id changing.
There are 1 chains and 0 blocks of water and 71 residues with 547 atoms

  chain  #res #atoms
  1 'G'    71    547

All occupancies are one
Opening force field file ./charmm36-mar2019.ff/atomtypes.atp
Reading residue database... (Charmm36-mar2019)
Opening force field file ./charmm36-mar2019.ff/merged.rtp
Opening force field file ./charmm36-mar2019.ff/merged.hdb
Opening force field file ./charmm36-mar2019.ff/merged.n.tdb
Opening force field file ./charmm36-mar2019.ff/merged.c.tdb
Processing chain 1 'G' (547 atoms, 71 residues)
Identified residue PHE41 as a starting terminus.
Identified residue ASP255 as a ending terminus.
8 out of 8 lines of specbond.dat converted successfully
Special Atom Distance matrix:
                   MET44  CYS189  CYS207  CYS223  CYS228  MET236  MET243
                    SD36    SG93   SG178   SG299   SG339   SD396   SD449
  CYS189    SG93   1.199
  CYS207   SG178   2.187   3.086
  CYS223   SG299   1.801   1.877   1.869
  CYS228   SG339   1.077   0.203   2.896   1.701
  MET236   SD396   2.244   2.534   1.514   0.796   2.341
  MET243   SD449   1.073   2.026   1.133   1.415   1.850   1.566
  CYS252   SG525   1.709   1.703   2.005   0.203   1.533   0.995   1.440


Linking CYS-189 SG-93 and CYS-228 SG-339...
Linking CYS-223 SG-299 and CYS-252 SG-525...
Start terminus PHE-41: NH3+
End terminus ASP-255: COO-
Opening force field file ./charmm36-mar2019.ff/merged.arn
Checking for duplicate atoms....
Generating any missing hydrogen atoms and/or adding termini.
Now there are 71 residues with 1095 atoms
Making bonds...
Warning: Long Bond (142-144 = 1.44485 nm)
Warning: Long Bond (327-329 = 0.997197 nm)
Number of bonds was 1107, now 1107
Generating angles, dihedrals and pairs...
Before cleaning: 2904 pairs
Before cleaning: 2924 dihedrals
Keeping all generated dihedrals
Making cmap torsions...
There are   69 cmap torsion pairs
There are 2924 dihedrals,  166 impropers, 2004 angles
          2883 pairs,     1107 bonds and     0 virtual sites
Total mass 7886.197 a.m.u.
Total charge 2.000 e
Writing topology

Writing coordinate file...
                --------- PLEASE NOTE ------------
You have successfully generated a topology from: 6TOU_clean.pdb.
The Charmm36-mar2019 force field and the tip3p water model are used.
                --------- ETON ESAELP ------------

GROMACS reminds you: "The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction." (Rachel Carson)

#editconf creation of lig.gro
```{bash}
gmx editconf -f ZINC22483429_H.pdb -o lig.gro

```

GROMACS:      gmx editconf, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx editconf -f ZINC22483429_H.pdb -o lig.gro

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 49 atoms
No velocities found

GROMACS reminds you: "People who do QM/MM must be rather patient and enjoy quality over speed" (Kresten Lindorff-Larsen)

#joining of conf.gro and lig.gro
```{bash}
gedit conf.gro lig.gro 
```

```{bash}
sed '1d;2d;$d' lig_2.gro >> lig_2.txt

```

sed -i '`wc -l < conf_2.gro`i\\r lig_2.txt' conf_2.gro


```{bash}
sed -i '`wc -l < conf_2.gro`i\\r lig_2.txt' conf_2.gro

```
sed -i '/3.344/r lig_2.txt' conf_2.gro

```{bash}
sed -i '`wc -l < conf.gro`ir lig_2.txt' conf_2.gro

```



ust with sed, without any pipes :

sed '1d;$d' file.txt
NOTE

1 mean first line
d mean delete
; is the separator for 2 commands
$ mean last line



#checking of conf.gro
```{bash}
chimera conf.gro 

```


#Joining of protein top and ligand itp
```{bash}
gedit topol.top ZINC22483429_H.itp

```
 
#editconf triclinic
```{bash}
gmx editconf -f conf.gro -o newbox.gro -bt triclinic -d 1.0

```
Command line:
  gmx editconf -f conf.gro -o newbox.gro -bt triclinic -d 1.0

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 1144 atoms
Volume: 34.0674 nm^3, corresponds to roughly 15300 electrons
No velocities found
    system size :  3.344  2.868  3.553 (nm)
    center      :  0.679 -3.231 -0.463 (nm)
    box vectors :  3.344  2.867  3.553 (nm)
    box angles  :  90.00  90.00  90.00 (degrees)
    box volume  :  34.07               (nm^3)
    shift       :  1.993  5.665  3.239 (nm)
new center      :  2.672  2.434  2.776 (nm)
new box vectors :  5.344  4.868  5.553 (nm)
new box angles  :  90.00  90.00  90.00 (degrees)
new box volume  : 144.46               (nm^3)

GROMACS reminds you: "There's a limit to how many times you can read how great you are and what an inspiration you are, but I'm not there yet." (Randy Pausch)
 

<!-- ```{bash} -->
<!-- gmx solvate -h -->

<!-- ``` -->

#solvation of the created space
```{bash}
gmx solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro

```


Command line:
  gmx editconf -f conf.gro -o newbox.gro -bt triclinic -d 1.0

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 1144 atoms
Volume: 34.0674 nm^3, corresponds to roughly 15300 electrons
No velocities found
    system size :  3.344  2.868  3.553 (nm)
    center      :  0.679 -3.231 -0.463 (nm)
    box vectors :  3.344  2.867  3.553 (nm)
    box angles  :  90.00  90.00  90.00 (degrees)
    box volume  :  34.07               (nm^3)
    shift       :  1.993  5.665  3.239 (nm)
new center      :  2.672  2.434  2.776 (nm)
new box vectors :  5.344  4.868  5.553 (nm)
new box angles  :  90.00  90.00  90.00 (degrees)
new box volume  : 144.46               (nm^3)

GROMACS reminds you: "There's a limit to how many times you can read how great you are and what an inspiration you are, but I'm not there yet." (Randy Pausch)

#checking for solvation
```{bash}
vmd solv.gro

```

#grompp checking of ions
```{bash}
gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr

```
GROMACS:      gmx grompp, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'ns_type'

NOTE 1 [file ions.mdp]:
  With Verlet lists the optimal nstlist is >= 10, with GPUs >= 20. Note
  that with the Verlet scheme, nstlist has no effect on the accuracy of
  your simulation.

Setting the LD random seed to -1003479506
Generated 105474 of the 105570 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 1
Generated 71356 of the 105570 1-4 parameter combinations
Excluding 3 bonded neighbours molecule type 'Protein_chain_G'
Excluding 3 bonded neighbours molecule type 'LIG'
Excluding 2 bonded neighbours molecule type 'SOL'

NOTE 2 [file topol.top, line 10394]:
  System has non-zero total charge: 2.000000
  Total charge should normally be an integer. See
  http://www.gromacs.org/Documentation/Floating_Point_Arithmetic
  for discussion on how close it should be to an integer.



Analysing residue names:
There are:    71    Protein residues
There are:     1      Other residues
There are:  4292      Water residues
Analysing Protein...
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Number of degrees of freedom in T-Coupling group rest is 29181.00

NOTE 3 [file ions.mdp]:
  You are using a plain Coulomb cut-off, which might produce artifacts.
  You might want to consider using PME electrostatics.


This run will generate roughly 1 Mb of data

There were 3 notes

GROMACS reminds you: "Why Weren't You at My Funeral ?" (G. Groenhof)

<!-- ```{bash} -->
<!-- gmx genion -h -->

<!-- ``` -->

#addition of ions and neutralization
```{bash}
gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -neutral

```


GROMACS:      gmx genion, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -neutral

Reading file ions.tpr, VERSION 2020.1 (single precision)
Reading file ions.tpr, VERSION 2020.1 (single precision)
Will try to add 0 NA ions and 2 CL ions.
Select a continuous group of solvent molecules
Group     0 (         System) has 14020 elements
Group     1 (        Protein) has  1095 elements
Group     2 (      Protein-H) has   548 elements
Group     3 (        C-alpha) has    71 elements
Group     4 (       Backbone) has   213 elements
Group     5 (      MainChain) has   283 elements
Group     6 (   MainChain+Cb) has   346 elements
Group     7 (    MainChain+H) has   354 elements
Group     8 (      SideChain) has   741 elements
Group     9 (    SideChain-H) has   265 elements
Group    10 (    Prot-Masses) has  1095 elements
Group    11 (    non-Protein) has 12925 elements
Group    12 (          Other) has    49 elements
Group    13 (            LIG) has    49 elements
Group    14 (          Water) has 12876 elements
Group    15 (            SOL) has 12876 elements
Group    16 (      non-Water) has  1144 elements
Select a group: 15
Selected 15: 'SOL'
Number of (3-atomic) solvent molecules: 4292

Processing topology
Replacing 2 solute molecules in topology file (topol.top)  by 0 NA and 2 CL ions.

Back Off! I just backed up topol.top to ./#topol.top.2#
Using random seed 2007641599.
Replacing solvent molecule 880 (atom 3784) with CL
Replacing solvent molecule 3837 (atom 12655) with CL


GROMACS reminds you: "What Kind Of Guru are You, Anyway ?" (F. Zappa)

#grompp
```{bash}
gmx grompp -f em.mdp -c solv_ions.gro -p topol.top -o em.tpr

```
GROMACS:      gmx grompp, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx grompp -f em.mdp -c solv_ions.gro -p topol.top -o em.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'ns_type'

NOTE 1 [file em.mdp]:
  With Verlet lists the optimal nstlist is >= 10, with GPUs >= 20. Note
  that with the Verlet scheme, nstlist has no effect on the accuracy of
  your simulation.

Setting the LD random seed to 238466828
Generated 105474 of the 105570 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 1
Generated 71356 of the 105570 1-4 parameter combinations
Excluding 3 bonded neighbours molecule type 'Protein_chain_G'
Excluding 3 bonded neighbours molecule type 'LIG'
Excluding 2 bonded neighbours molecule type 'SOL'
Excluding 1 bonded neighbours molecule type 'CL'
Analysing residue names:
There are:    71    Protein residues
There are:     1      Other residues
There are:  4290      Water residues
There are:     2        Ion residues
Analysing Protein...
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Number of degrees of freedom in T-Coupling group rest is 29175.00
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 48x42x48, spacing 0.111 0.116 0.116
Estimate for the relative computational load of the PME mesh part: 0.18
This run will generate roughly 1 Mb of data

There was 1 note

GROMACS reminds you: "I Was Born to Have Adventure" (F. Zappa)

#mdrun energy minimization
```{bash}
gmx mdrun -v -deffnm em

```
GROMACS:      gmx mdrun, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx mdrun -v -deffnm em

Reading file em.tpr, VERSION 2020.1 (single precision)
1 GPU selected for this run.
Mapping of GPU IDs to the 1 GPU task in the 1 rank on this node:
  PP:0
PP tasks will do (non-perturbed) short-ranged interactions on the GPU
PP task will update and constrain coordinates on the CPU
Using 1 MPI thread

Non-default thread affinity set, disabling internal thread affinity

Using 16 OpenMP threads


Steepest Descents:
   Tolerance (Fmax)   =  1.00000e+03
   Number of steps    =        50000
Step=    0, Dmax= 1.0e-02 nm, Epot=  3.20255e+05 Fmax= 4.14313e+05, atom= 142
Step=    1, Dmax= 1.0e-02 nm, Epot=  2.93931e+05 Fmax= 4.04690e+05, atom= 142
Step=    2, Dmax= 1.2e-02 nm, Epot=  2.69360e+05 Fmax= 3.94140e+05, atom= 142
Step=    3, Dmax= 1.4e-02 nm, Epot=  2.44720e+05 Fmax= 3.83135e+05, atom= 142
Step=    4, Dmax= 1.7e-02 nm, Epot=  2.19137e+05 Fmax= 3.72012e+05, atom= 142
Step=    5, Dmax= 2.1e-02 nm, Epot=  1.92094e+05 Fmax= 3.58359e+05, atom= 142
Step=    6, Dmax= 2.5e-02 nm, Epot=  1.63387e+05 Fmax= 3.33515e+05, atom= 142
Step=    7, Dmax= 3.0e-02 nm, Epot=  1.33083e+05 Fmax= 2.83998e+05, atom= 144
Step=    8, Dmax= 3.6e-02 nm, Epot=  1.01547e+05 Fmax= 2.51280e+05, atom= 144
Step=    9, Dmax= 4.3e-02 nm, Epot=  7.02764e+04 Fmax= 2.53996e+05, atom= 142
Step=   10, Dmax= 5.2e-02 nm, Epot=  3.91415e+04 Fmax= 1.68019e+05, atom= 144
Step=   11, Dmax= 6.2e-02 nm, Epot=  5.67391e+03 Fmax= 1.44857e+05, atom= 142
Step=   12, Dmax= 7.4e-02 nm, Epot= -2.32377e+04 Fmax= 9.72488e+04, atom= 142
Step=   13, Dmax= 8.9e-02 nm, Epot= -4.61113e+04 Fmax= 3.81642e+05, atom= 327
Step=   14, Dmax= 1.1e-01 nm, Epot= -5.26565e+04 Fmax= 1.30254e+05, atom= 327
Step=   15, Dmax= 1.3e-01 nm, Epot= -7.93082e+04 Fmax= 1.85248e+05, atom= 327
Step=   16, Dmax= 1.5e-01 nm, Epot= -8.14431e+04 Fmax= 1.60971e+05, atom= 327
Step=   17, Dmax= 1.8e-01 nm, Epot= -9.35587e+04 Fmax= 3.09082e+05, atom= 327
Step=   19, Dmax= 1.1e-01 nm, Epot= -1.05410e+05 Fmax= 5.22683e+04, atom= 327
Step=   21, Dmax= 6.7e-02 nm, Epot= -1.13282e+05 Fmax= 1.38546e+05, atom= 142
Step=   22, Dmax= 8.0e-02 nm, Epot= -1.15262e+05 Fmax= 8.53523e+04, atom= 142
Step=   23, Dmax= 9.6e-02 nm, Epot= -1.21906e+05 Fmax= 7.29781e+04, atom= 142
Step=   25, Dmax= 5.8e-02 nm, Epot= -1.25157e+05 Fmax= 5.90042e+04, atom= 142
Step=   26, Dmax= 6.9e-02 nm, Epot= -1.28888e+05 Fmax= 7.10019e+04, atom= 142
Step=   28, Dmax= 4.1e-02 nm, Epot= -1.31972e+05 Fmax= 3.18585e+04, atom= 142
Step=   29, Dmax= 5.0e-02 nm, Epot= -1.35047e+05 Fmax= 5.06820e+04, atom= 142
Step=   30, Dmax= 6.0e-02 nm, Epot= -1.35988e+05 Fmax= 6.58679e+04, atom= 142
Step=   31, Dmax= 7.2e-02 nm, Epot= -1.38616e+05 Fmax= 1.31677e+05, atom= 142
Step=   33, Dmax= 4.3e-02 nm, Epot= -1.40585e+05 Fmax= 2.86084e+04, atom= 142
Step=   34, Dmax= 5.2e-02 nm, Epot= -1.42789e+05 Fmax= 6.33595e+04, atom= 142
Step=   35, Dmax= 6.2e-02 nm, Epot= -1.43293e+05 Fmax= 4.96676e+04, atom= 142
Step=   36, Dmax= 7.4e-02 nm, Epot= -1.44553e+05 Fmax= 7.75987e+04, atom= 142
Step=   37, Dmax= 8.9e-02 nm, Epot= -1.44981e+05 Fmax= 7.57601e+04, atom= 142
Step=   39, Dmax= 5.3e-02 nm, Epot= -1.49209e+05 Fmax= 1.02348e+04, atom= 142
Step=   40, Dmax= 6.4e-02 nm, Epot= -1.52233e+05 Fmax= 8.46374e+04, atom= 142
Step=   41, Dmax= 7.7e-02 nm, Epot= -1.53691e+05 Fmax= 5.25148e+04, atom= 142
Step=   43, Dmax= 4.6e-02 nm, Epot= -1.57029e+05 Fmax= 8.69565e+03, atom= 146
Step=   44, Dmax= 5.5e-02 nm, Epot= -1.57740e+05 Fmax= 4.22969e+04, atom= 144
Step=   45, Dmax= 6.6e-02 nm, Epot= -1.59842e+05 Fmax= 7.65595e+04, atom= 1107
Step=   46, Dmax= 8.0e-02 nm, Epot= -1.60438e+05 Fmax= 4.80696e+04, atom= 1107
Step=   48, Dmax= 4.8e-02 nm, Epot= -1.63290e+05 Fmax= 1.06203e+04, atom= 3277
Step=   50, Dmax= 2.9e-02 nm, Epot= -1.63970e+05 Fmax= 3.33185e+04, atom= 327
Step=   51, Dmax= 3.4e-02 nm, Epot= -1.64948e+05 Fmax= 1.91437e+04, atom= 327
Step=   53, Dmax= 2.1e-02 nm, Epot= -1.65740e+05 Fmax= 1.29373e+04, atom= 329
Step=   55, Dmax= 1.2e-02 nm, Epot= -1.66315e+05 Fmax= 9.57553e+03, atom= 144
Step=   56, Dmax= 1.5e-02 nm, Epot= -1.66616e+05 Fmax= 6.34466e+04, atom= 144
Step=   57, Dmax= 1.8e-02 nm, Epot= -1.67104e+05 Fmax= 6.27282e+03, atom= 144
Step=   58, Dmax= 2.1e-02 nm, Epot= -1.67786e+05 Fmax= 3.48839e+04, atom= 142
Step=   59, Dmax= 2.6e-02 nm, Epot= -1.68579e+05 Fmax= 1.60739e+04, atom= 144
Step=   60, Dmax= 3.1e-02 nm, Epot= -1.68725e+05 Fmax= 2.61087e+04, atom= 144
Step=   61, Dmax= 3.7e-02 nm, Epot= -1.69353e+05 Fmax= 1.93795e+04, atom= 329
Step=   63, Dmax= 2.2e-02 nm, Epot= -1.70218e+05 Fmax= 1.29024e+04, atom= 329
Step=   65, Dmax= 1.3e-02 nm, Epot= -1.70774e+05 Fmax= 7.89590e+03, atom= 329
Step=   66, Dmax= 1.6e-02 nm, Epot= -1.71197e+05 Fmax= 2.37875e+04, atom= 329
Step=   67, Dmax= 1.9e-02 nm, Epot= -1.71719e+05 Fmax= 1.04418e+04, atom= 329
Step=   68, Dmax= 2.3e-02 nm, Epot= -1.71986e+05 Fmax= 3.93220e+04, atom= 329
Step=   69, Dmax= 2.8e-02 nm, Epot= -1.72574e+05 Fmax= 1.43396e+04, atom= 329
Step=   71, Dmax= 1.7e-02 nm, Epot= -1.72996e+05 Fmax= 7.82930e+03, atom= 327
Step=   72, Dmax= 2.0e-02 nm, Epot= -1.73261e+05 Fmax= 2.80368e+04, atom= 327
Step=   73, Dmax= 2.4e-02 nm, Epot= -1.73905e+05 Fmax= 1.21169e+04, atom= 327
Step=   75, Dmax= 1.4e-02 nm, Epot= -1.74286e+05 Fmax= 6.96741e+03, atom= 327
Step=   77, Dmax= 8.6e-03 nm, Epot= -1.74614e+05 Fmax= 9.03785e+03, atom= 142
Step=   78, Dmax= 1.0e-02 nm, Epot= -1.74917e+05 Fmax= 9.40280e+03, atom= 142
Step=   79, Dmax= 1.2e-02 nm, Epot= -1.75175e+05 Fmax= 1.27989e+04, atom= 142
Step=   80, Dmax= 1.5e-02 nm, Epot= -1.75448e+05 Fmax= 1.31296e+04, atom= 142
Step=   81, Dmax= 1.8e-02 nm, Epot= -1.75616e+05 Fmax= 1.67119e+04, atom= 144
Step=   82, Dmax= 2.1e-02 nm, Epot= -1.75753e+05 Fmax= 2.00325e+04, atom= 1120
Step=   83, Dmax= 2.6e-02 nm, Epot= -1.75833e+05 Fmax= 2.69845e+04, atom= 1120
Step=   84, Dmax= 3.1e-02 nm, Epot= -1.76131e+05 Fmax= 2.90682e+04, atom= 1120
Step=   86, Dmax= 1.8e-02 nm, Epot= -1.77007e+05 Fmax= 4.64775e+03, atom= 1120
Step=   87, Dmax= 2.2e-02 nm, Epot= -1.77101e+05 Fmax= 3.55203e+04, atom= 1120
Step=   88, Dmax= 2.7e-02 nm, Epot= -1.78133e+05 Fmax= 1.30879e+04, atom= 1120
Step=   90, Dmax= 1.6e-02 nm, Epot= -1.78324e+05 Fmax= 1.59073e+04, atom= 1120
Step=   91, Dmax= 1.9e-02 nm, Epot= -1.78488e+05 Fmax= 1.91543e+04, atom= 1120
Step=   92, Dmax= 2.3e-02 nm, Epot= -1.78614e+05 Fmax= 2.26400e+04, atom= 1120
Step=   93, Dmax= 2.8e-02 nm, Epot= -1.78659e+05 Fmax= 2.78684e+04, atom= 1120
Step=   94, Dmax= 3.3e-02 nm, Epot= -1.78671e+05 Fmax= 3.23659e+04, atom= 1120
Step=   96, Dmax= 2.0e-02 nm, Epot= -1.79602e+05 Fmax= 3.86402e+03, atom= 1120
Step=   98, Dmax= 1.2e-02 nm, Epot= -1.79957e+05 Fmax= 1.76691e+04, atom= 1120
Step=   99, Dmax= 1.4e-02 nm, Epot= -1.80296e+05 Fmax= 8.45338e+03, atom= 1120
Step=  100, Dmax= 1.7e-02 nm, Epot= -1.80316e+05 Fmax= 2.26562e+04, atom= 1120
Step=  101, Dmax= 2.1e-02 nm, Epot= -1.80707e+05 Fmax= 1.49707e+04, atom= 1120
Step=  103, Dmax= 1.2e-02 nm, Epot= -1.80981e+05 Fmax= 7.48828e+03, atom= 1120
Step=  104, Dmax= 1.5e-02 nm, Epot= -1.81065e+05 Fmax= 1.97418e+04, atom= 1120
Step=  105, Dmax= 1.8e-02 nm, Epot= -1.81395e+05 Fmax= 1.26226e+04, atom= 1120
Step=  107, Dmax= 1.1e-02 nm, Epot= -1.81626e+05 Fmax= 6.89571e+03, atom= 1120
Step=  108, Dmax= 1.3e-02 nm, Epot= -1.81758e+05 Fmax= 1.62990e+04, atom= 1120
Step=  109, Dmax= 1.5e-02 nm, Epot= -1.82013e+05 Fmax= 1.18064e+04, atom= 1120
Step=  111, Dmax= 9.2e-03 nm, Epot= -1.82227e+05 Fmax= 4.94567e+03, atom= 1120
Step=  112, Dmax= 1.1e-02 nm, Epot= -1.82413e+05 Fmax= 1.54355e+04, atom= 1120
Step=  113, Dmax= 1.3e-02 nm, Epot= -1.82672e+05 Fmax= 8.70685e+03, atom= 1120
Step=  114, Dmax= 1.6e-02 nm, Epot= -1.82679e+05 Fmax= 2.05607e+04, atom= 1120
Step=  115, Dmax= 1.9e-02 nm, Epot= -1.82989e+05 Fmax= 1.42275e+04, atom= 1120
Step=  117, Dmax= 1.1e-02 nm, Epot= -1.83235e+05 Fmax= 6.74973e+03, atom= 1120
Step=  118, Dmax= 1.4e-02 nm, Epot= -1.83304e+05 Fmax= 1.81731e+04, atom= 1120
Step=  119, Dmax= 1.7e-02 nm, Epot= -1.83585e+05 Fmax= 1.20342e+04, atom= 1120
Step=  121, Dmax= 9.9e-03 nm, Epot= -1.83787e+05 Fmax= 5.97088e+03, atom= 1120
Step=  122, Dmax= 1.2e-02 nm, Epot= -1.83895e+05 Fmax= 1.59116e+04, atom= 1120
Step=  123, Dmax= 1.4e-02 nm, Epot= -1.84138e+05 Fmax= 1.00383e+04, atom= 1120
Step=  125, Dmax= 8.6e-03 nm, Epot= -1.84311e+05 Fmax= 5.64466e+03, atom= 1120
Step=  126, Dmax= 1.0e-02 nm, Epot= -1.84446e+05 Fmax= 1.29305e+04, atom= 1120
Step=  127, Dmax= 1.2e-02 nm, Epot= -1.84634e+05 Fmax= 9.64279e+03, atom= 1120
Step=  128, Dmax= 1.5e-02 nm, Epot= -1.84669e+05 Fmax= 1.71890e+04, atom= 1120
Step=  129, Dmax= 1.8e-02 nm, Epot= -1.84856e+05 Fmax= 1.53062e+04, atom= 1120
Step=  131, Dmax= 1.1e-02 nm, Epot= -1.85119e+05 Fmax= 4.07134e+03, atom= 1120
Step=  132, Dmax= 1.3e-02 nm, Epot= -1.85222e+05 Fmax= 1.95654e+04, atom= 1120
Step=  133, Dmax= 1.5e-02 nm, Epot= -1.85570e+05 Fmax= 8.36055e+03, atom= 1120
Step=  135, Dmax= 9.2e-03 nm, Epot= -1.85704e+05 Fmax= 8.52226e+03, atom= 1120
Step=  136, Dmax= 1.1e-02 nm, Epot= -1.85810e+05 Fmax= 1.14999e+04, atom= 1120
Step=  137, Dmax= 1.3e-02 nm, Epot= -1.85924e+05 Fmax= 1.27880e+04, atom= 1120
Step=  138, Dmax= 1.6e-02 nm, Epot= -1.85990e+05 Fmax= 1.60925e+04, atom= 1120
Step=  139, Dmax= 1.9e-02 nm, Epot= -1.86052e+05 Fmax= 1.88648e+04, atom= 1120
Step=  140, Dmax= 2.3e-02 nm, Epot= -1.86053e+05 Fmax= 2.27729e+04, atom= 1120
Step=  142, Dmax= 1.4e-02 nm, Epot= -1.86547e+05 Fmax= 2.32519e+03, atom= 1120
Step=  143, Dmax= 1.7e-02 nm, Epot= -1.86730e+05 Fmax= 2.71783e+04, atom= 1120
Step=  144, Dmax= 2.0e-02 nm, Epot= -1.87357e+05 Fmax= 8.99919e+03, atom= 1120
Step=  146, Dmax= 1.2e-02 nm, Epot= -1.87431e+05 Fmax= 1.25161e+04, atom= 1120
Step=  147, Dmax= 1.4e-02 nm, Epot= -1.87529e+05 Fmax= 1.35961e+04, atom= 1120
Step=  148, Dmax= 1.7e-02 nm, Epot= -1.87556e+05 Fmax= 1.74475e+04, atom= 1120
Step=  149, Dmax= 2.1e-02 nm, Epot= -1.87596e+05 Fmax= 2.01331e+04, atom= 1120
Step=  151, Dmax= 1.2e-02 nm, Epot= -1.87990e+05 Fmax= 2.29099e+03, atom= 1120
Step=  152, Dmax= 1.5e-02 nm, Epot= -1.88102e+05 Fmax= 2.53249e+04, atom= 1120
Step=  153, Dmax= 1.8e-02 nm, Epot= -1.88663e+05 Fmax= 7.00537e+03, atom= 1120
Step=  155, Dmax= 1.1e-02 nm, Epot= -1.88718e+05 Fmax= 1.25384e+04, atom= 1120
Step=  156, Dmax= 1.3e-02 nm, Epot= -1.88848e+05 Fmax= 1.06434e+04, atom= 1120
Step=  158, Dmax= 7.7e-03 nm, Epot= -1.89003e+05 Fmax= 3.37978e+03, atom= 1120
Step=  159, Dmax= 9.2e-03 nm, Epot= -1.89115e+05 Fmax= 1.31326e+04, atom= 1120
Step=  160, Dmax= 1.1e-02 nm, Epot= -1.89298e+05 Fmax= 7.05288e+03, atom= 1120
Step=  162, Dmax= 6.6e-03 nm, Epot= -1.89403e+05 Fmax= 4.92764e+03, atom= 1120
Step=  163, Dmax= 7.9e-03 nm, Epot= -1.89489e+05 Fmax= 9.70404e+03, atom= 1120
Step=  164, Dmax= 9.5e-03 nm, Epot= -1.89606e+05 Fmax= 7.57916e+03, atom= 1120
Step=  165, Dmax= 1.1e-02 nm, Epot= -1.89634e+05 Fmax= 1.34283e+04, atom= 1120
Step=  166, Dmax= 1.4e-02 nm, Epot= -1.89762e+05 Fmax= 1.14933e+04, atom= 1120
Step=  168, Dmax= 8.2e-03 nm, Epot= -1.89928e+05 Fmax= 3.57756e+03, atom= 1120
Step=  169, Dmax= 9.9e-03 nm, Epot= -1.89998e+05 Fmax= 1.41828e+04, atom= 1120
Step=  170, Dmax= 1.2e-02 nm, Epot= -1.90197e+05 Fmax= 7.51112e+03, atom= 1120
Step=  172, Dmax= 7.1e-03 nm, Epot= -1.90299e+05 Fmax= 5.37240e+03, atom= 1120
Step=  173, Dmax= 8.5e-03 nm, Epot= -1.90364e+05 Fmax= 1.03445e+04, atom= 1120
Step=  174, Dmax= 1.0e-02 nm, Epot= -1.90477e+05 Fmax= 8.23998e+03, atom= 1120
Step=  175, Dmax= 1.2e-02 nm, Epot= -1.90479e+05 Fmax= 1.43322e+04, atom= 1120
Step=  176, Dmax= 1.5e-02 nm, Epot= -1.90603e+05 Fmax= 1.24635e+04, atom= 1120
Step=  178, Dmax= 8.9e-03 nm, Epot= -1.90788e+05 Fmax= 3.73049e+03, atom= 1120
Step=  179, Dmax= 1.1e-02 nm, Epot= -1.90812e+05 Fmax= 1.53742e+04, atom= 1120
Step=  180, Dmax= 1.3e-02 nm, Epot= -1.91035e+05 Fmax= 7.93889e+03, atom= 1120
Step=  182, Dmax= 7.7e-03 nm, Epot= -1.91134e+05 Fmax= 5.98805e+03, atom= 1112
Step=  183, Dmax= 9.2e-03 nm, Epot= -1.91180e+05 Fmax= 1.07597e+04, atom= 1120
Step=  184, Dmax= 1.1e-02 nm, Epot= -1.91284e+05 Fmax= 9.34520e+03, atom= 1112
Step=  186, Dmax= 6.6e-03 nm, Epot= -1.91409e+05 Fmax= 2.72406e+03, atom= 1120
Step=  187, Dmax= 7.9e-03 nm, Epot= -1.91513e+05 Fmax= 1.16998e+04, atom= 1112
Step=  188, Dmax= 9.5e-03 nm, Epot= -1.91666e+05 Fmax= 5.63887e+03, atom= 1112
Step=  190, Dmax= 5.7e-03 nm, Epot= -1.91749e+05 Fmax= 4.82486e+03, atom= 1112
Step=  191, Dmax= 6.9e-03 nm, Epot= -1.91822e+05 Fmax= 7.63155e+03, atom= 1112
Step=  192, Dmax= 8.2e-03 nm, Epot= -1.91903e+05 Fmax= 7.41812e+03, atom= 1112
Step=  193, Dmax= 9.9e-03 nm, Epot= -1.91949e+05 Fmax= 1.05526e+04, atom= 1112
Step=  194, Dmax= 1.2e-02 nm, Epot= -1.92019e+05 Fmax= 1.10992e+04, atom= 1112
Step=  195, Dmax= 1.4e-02 nm, Epot= -1.92025e+05 Fmax= 1.48101e+04, atom= 1112
Step=  196, Dmax= 1.7e-02 nm, Epot= -1.92065e+05 Fmax= 1.63478e+04, atom= 1112
Step=  198, Dmax= 1.0e-02 nm, Epot= -1.92336e+05 Fmax= 2.29136e+03, atom= 1112
Step=  199, Dmax= 1.2e-02 nm, Epot= -1.92354e+05 Fmax= 2.03221e+04, atom= 1112
Step=  200, Dmax= 1.5e-02 nm, Epot= -1.92721e+05 Fmax= 6.54031e+03, atom= 1112
Step=  202, Dmax= 8.8e-03 nm, Epot= -1.92768e+05 Fmax= 9.63629e+03, atom= 1112
Step=  203, Dmax= 1.1e-02 nm, Epot= -1.92839e+05 Fmax= 9.69558e+03, atom= 1112
Step=  204, Dmax= 1.3e-02 nm, Epot= -1.92849e+05 Fmax= 1.35748e+04, atom= 1112
Step=  205, Dmax= 1.5e-02 nm, Epot= -1.92905e+05 Fmax= 1.42862e+04, atom= 1112
Step=  207, Dmax= 9.2e-03 nm, Epot= -1.93115e+05 Fmax= 2.48001e+03, atom= 1112
Step=  208, Dmax= 1.1e-02 nm, Epot= -1.93147e+05 Fmax= 1.74586e+04, atom= 1112
Step=  209, Dmax= 1.3e-02 nm, Epot= -1.93412e+05 Fmax= 6.67170e+03, atom= 1112
Step=  211, Dmax= 7.9e-03 nm, Epot= -1.93472e+05 Fmax= 7.74756e+03, atom= 1112
Step=  212, Dmax= 9.5e-03 nm, Epot= -1.93521e+05 Fmax= 9.63417e+03, atom= 1112
Step=  213, Dmax= 1.1e-02 nm, Epot= -1.93567e+05 Fmax= 1.11523e+04, atom= 1112
Step=  214, Dmax= 1.4e-02 nm, Epot= -1.93586e+05 Fmax= 1.38560e+04, atom= 1112
Step=  215, Dmax= 1.6e-02 nm, Epot= -1.93601e+05 Fmax= 1.61027e+04, atom= 1112
Step=  217, Dmax= 9.9e-03 nm, Epot= -1.93848e+05 Fmax= 1.92057e+03, atom= 1112
Step=  218, Dmax= 1.2e-02 nm, Epot= -1.93907e+05 Fmax= 1.94740e+04, atom= 1112
Step=  219, Dmax= 1.4e-02 nm, Epot= -1.94221e+05 Fmax= 6.46515e+03, atom= 1112
Step=  221, Dmax= 8.5e-03 nm, Epot= -1.94263e+05 Fmax= 9.04223e+03, atom= 1112
Step=  222, Dmax= 1.0e-02 nm, Epot= -1.94318e+05 Fmax= 9.63346e+03, atom= 1112
Step=  223, Dmax= 1.2e-02 nm, Epot= -1.94334e+05 Fmax= 1.27200e+04, atom= 1112
Step=  224, Dmax= 1.5e-02 nm, Epot= -1.94368e+05 Fmax= 1.41569e+04, atom= 1112
Step=  226, Dmax= 8.8e-03 nm, Epot= -1.94559e+05 Fmax= 1.92633e+03, atom= 1112
Step=  227, Dmax= 1.1e-02 nm, Epot= -1.94618e+05 Fmax= 1.75673e+04, atom= 1112
Step=  228, Dmax= 1.3e-02 nm, Epot= -1.94874e+05 Fmax= 5.60886e+03, atom= 1112
Step=  230, Dmax= 7.6e-03 nm, Epot= -1.94917e+05 Fmax= 8.34353e+03, atom= 1112
Step=  231, Dmax= 9.2e-03 nm, Epot= -1.94974e+05 Fmax= 8.33600e+03, atom= 1112
Step=  232, Dmax= 1.1e-02 nm, Epot= -1.94989e+05 Fmax= 1.17367e+04, atom= 1112
Step=  233, Dmax= 1.3e-02 nm, Epot= -1.95037e+05 Fmax= 1.22995e+04, atom= 1112
Step=  235, Dmax= 7.9e-03 nm, Epot= -1.95183e+05 Fmax= 2.16107e+03, atom= 1112
Step=  236, Dmax= 9.5e-03 nm, Epot= -1.95237e+05 Fmax= 1.50491e+04, atom= 1112
Step=  237, Dmax= 1.1e-02 nm, Epot= -1.95422e+05 Fmax= 5.76372e+03, atom= 1112
Step=  239, Dmax= 6.8e-03 nm, Epot= -1.95472e+05 Fmax= 6.67793e+03, atom= 1112
Step=  240, Dmax= 8.2e-03 nm, Epot= -1.95514e+05 Fmax= 8.31435e+03, atom= 1112
Step=  241, Dmax= 9.8e-03 nm, Epot= -1.95553e+05 Fmax= 9.61913e+03, atom= 1112
Step=  242, Dmax= 1.2e-02 nm, Epot= -1.95576e+05 Fmax= 1.19534e+04, atom= 1112
Step=  243, Dmax= 1.4e-02 nm, Epot= -1.95595e+05 Fmax= 1.38909e+04, atom= 1112
Step=  245, Dmax= 8.5e-03 nm, Epot= -1.95767e+05 Fmax= 1.65361e+03, atom= 1112
Step=  246, Dmax= 1.0e-02 nm, Epot= -1.95852e+05 Fmax= 1.68117e+04, atom= 1112
Step=  247, Dmax= 1.2e-02 nm, Epot= -1.96071e+05 Fmax= 5.56076e+03, atom= 1112
Step=  249, Dmax= 7.3e-03 nm, Epot= -1.96109e+05 Fmax= 7.81844e+03, atom= 1112
Step=  250, Dmax= 8.8e-03 nm, Epot= -1.96155e+05 Fmax= 8.29103e+03, atom= 1112
Step=  251, Dmax= 1.1e-02 nm, Epot= -1.96174e+05 Fmax= 1.09928e+04, atom= 1112
Step=  252, Dmax= 1.3e-02 nm, Epot= -1.96206e+05 Fmax= 1.21916e+04, atom= 1112
Step=  254, Dmax= 7.6e-03 nm, Epot= -1.96340e+05 Fmax= 1.68525e+03, atom= 1112
Step=  255, Dmax= 9.1e-03 nm, Epot= -1.96417e+05 Fmax= 1.51170e+04, atom= 1112
Step=  256, Dmax= 1.1e-02 nm, Epot= -1.96596e+05 Fmax= 4.87754e+03, atom= 1112
Step=  258, Dmax= 6.6e-03 nm, Epot= -1.96634e+05 Fmax= 7.15722e+03, atom= 1112
Step=  259, Dmax= 7.9e-03 nm, Epot= -1.96680e+05 Fmax= 7.23235e+03, atom= 1112
Step=  260, Dmax= 9.5e-03 nm, Epot= -1.96701e+05 Fmax= 1.00826e+04, atom= 1112
Step=  261, Dmax= 1.1e-02 nm, Epot= -1.96740e+05 Fmax= 1.06523e+04, atom= 1112
Step=  263, Dmax= 6.8e-03 nm, Epot= -1.96845e+05 Fmax= 1.82018e+03, atom= 1112
Step=  264, Dmax= 8.2e-03 nm, Epot= -1.96916e+05 Fmax= 1.30265e+04, atom= 1112
Step=  265, Dmax= 9.8e-03 nm, Epot= -1.97048e+05 Fmax= 4.92527e+03, atom= 1112
Step=  267, Dmax= 5.9e-03 nm, Epot= -1.97090e+05 Fmax= 5.80856e+03, atom= 1112
Step=  268, Dmax= 7.1e-03 nm, Epot= -1.97128e+05 Fmax= 7.12327e+03, atom= 1112
Step=  269, Dmax= 8.5e-03 nm, Epot= -1.97162e+05 Fmax= 8.34767e+03, atom= 1112
Step=  270, Dmax= 1.0e-02 nm, Epot= -1.97187e+05 Fmax= 1.02609e+04, atom= 1112
Step=  271, Dmax= 1.2e-02 nm, Epot= -1.97207e+05 Fmax= 1.20330e+04, atom= 1112
Step=  273, Dmax= 7.3e-03 nm, Epot= -1.97329e+05 Fmax= 1.37419e+03, atom= 1112
Step=  274, Dmax= 8.8e-03 nm, Epot= -1.97437e+05 Fmax= 1.45525e+04, atom= 1112
Step=  275, Dmax= 1.1e-02 nm, Epot= -1.97593e+05 Fmax= 4.74418e+03, atom= 1112
Step=  277, Dmax= 6.3e-03 nm, Epot= -1.97628e+05 Fmax= 6.79798e+03, atom= 1112
Step=  278, Dmax= 7.6e-03 nm, Epot= -1.97668e+05 Fmax= 7.09783e+03, atom= 1112
Step=  279, Dmax= 9.1e-03 nm, Epot= -1.97688e+05 Fmax= 9.53724e+03, atom= 1112
Step=  280, Dmax= 1.1e-02 nm, Epot= -1.97719e+05 Fmax= 1.04621e+04, atom= 1112
Step=  282, Dmax= 6.6e-03 nm, Epot= -1.97814e+05 Fmax= 1.51029e+03, atom= 1112
Step=  283, Dmax= 7.9e-03 nm, Epot= -1.97896e+05 Fmax= 1.29724e+04, atom= 1112
Step=  284, Dmax= 9.5e-03 nm, Epot= -1.98022e+05 Fmax= 4.27657e+03, atom= 1112
Step=  286, Dmax= 5.7e-03 nm, Epot= -1.98058e+05 Fmax= 6.10450e+03, atom= 1112
Step=  287, Dmax= 6.8e-03 nm, Epot= -1.98096e+05 Fmax= 6.30859e+03, atom= 1112
Step=  288, Dmax= 8.2e-03 nm, Epot= -1.98120e+05 Fmax= 8.62757e+03, atom= 1112
Step=  289, Dmax= 9.8e-03 nm, Epot= -1.98152e+05 Fmax= 9.25879e+03, atom= 1112
Step=  290, Dmax= 1.2e-02 nm, Epot= -1.98155e+05 Fmax= 1.22365e+04, atom= 1112
Step=  291, Dmax= 1.4e-02 nm, Epot= -1.98174e+05 Fmax= 1.35343e+04, atom= 1112
Step=  293, Dmax= 8.5e-03 nm, Epot= -1.98313e+05 Fmax= 1.95606e+03, atom= 1112
Step=  294, Dmax= 1.0e-02 nm, Epot= -1.98320e+05 Fmax= 1.65165e+04, atom= 1112
Step=  295, Dmax= 1.2e-02 nm, Epot= -1.98499e+05 Fmax= 5.77985e+03, atom= 1112
Step=  297, Dmax= 7.3e-03 nm, Epot= -1.98527e+05 Fmax= 7.56457e+03, atom= 1112
Step=  298, Dmax= 8.8e-03 nm, Epot= -1.98557e+05 Fmax= 8.48781e+03, atom= 1112
Step=  299, Dmax= 1.1e-02 nm, Epot= -1.98571e+05 Fmax= 1.07421e+04, atom= 1112
Step=  300, Dmax= 1.3e-02 nm, Epot= -1.98587e+05 Fmax= 1.23621e+04, atom= 1112
Step=  302, Dmax= 7.6e-03 nm, Epot= -1.98703e+05 Fmax= 1.47432e+03, atom= 1112
Step=  303, Dmax= 9.1e-03 nm, Epot= -1.98761e+05 Fmax= 1.52573e+04, atom= 1112
Step=  304, Dmax= 1.1e-02 nm, Epot= -1.98917e+05 Fmax= 4.67867e+03, atom= 1112
Step=  306, Dmax= 6.6e-03 nm, Epot= -1.98943e+05 Fmax= 7.30974e+03, atom= 1112
Step=  307, Dmax= 7.9e-03 nm, Epot= -1.98980e+05 Fmax= 7.04103e+03, atom= 1112
Step=  308, Dmax= 9.4e-03 nm, Epot= -1.98988e+05 Fmax= 1.02111e+04, atom= 1112
Step=  309, Dmax= 1.1e-02 nm, Epot= -1.99020e+05 Fmax= 1.04642e+04, atom= 1112
Step=  311, Dmax= 6.8e-03 nm, Epot= -1.99107e+05 Fmax= 1.96468e+03, atom= 1112
Step=  312, Dmax= 8.2e-03 nm, Epot= -1.99137e+05 Fmax= 1.28674e+04, atom= 1112
Step=  313, Dmax= 9.8e-03 nm, Epot= -1.99248e+05 Fmax= 5.02285e+03, atom= 1112
Step=  315, Dmax= 5.9e-03 nm, Epot= -1.99279e+05 Fmax= 5.68333e+03, atom= 1112
Step=  316, Dmax= 7.0e-03 nm, Epot= -1.99306e+05 Fmax= 7.20119e+03, atom= 1112
Step=  317, Dmax= 8.5e-03 nm, Epot= -1.99332e+05 Fmax= 8.22660e+03, atom= 1112
Step=  318, Dmax= 1.0e-02 nm, Epot= -1.99346e+05 Fmax= 1.03160e+04, atom= 1112
Step=  319, Dmax= 1.2e-02 nm, Epot= -1.99360e+05 Fmax= 1.19128e+04, atom= 1112
Step=  321, Dmax= 7.3e-03 nm, Epot= -1.99464e+05 Fmax= 1.44820e+03, atom= 1112
Step=  322, Dmax= 8.8e-03 nm, Epot= -1.99520e+05 Fmax= 1.44688e+04, atom= 1112
Step=  323, Dmax= 1.1e-02 nm, Epot= -1.99654e+05 Fmax= 4.76256e+03, atom= 1112
Step=  325, Dmax= 6.3e-03 nm, Epot= -1.99680e+05 Fmax= 6.74906e+03, atom= 1112
Step=  326, Dmax= 7.6e-03 nm, Epot= -1.99710e+05 Fmax= 7.09668e+03, atom= 1112
Step=  327, Dmax= 9.1e-03 nm, Epot= -1.99723e+05 Fmax= 9.49138e+03, atom= 1112
Step=  328, Dmax= 1.1e-02 nm, Epot= -1.99745e+05 Fmax= 1.04384e+04, atom= 1112
Step=  330, Dmax= 6.5e-03 nm, Epot= -1.99827e+05 Fmax= 1.49862e+03, atom= 1112
Step=  331, Dmax= 7.9e-03 nm, Epot= -1.99880e+05 Fmax= 1.29126e+04, atom= 1112
Step=  332, Dmax= 9.4e-03 nm, Epot= -1.99988e+05 Fmax= 4.28467e+03, atom= 1112
Step=  334, Dmax= 5.7e-03 nm, Epot= -2.00015e+05 Fmax= 6.05655e+03, atom= 1112
Step=  335, Dmax= 6.8e-03 nm, Epot= -2.00044e+05 Fmax= 6.32211e+03, atom= 1112
Step=  336, Dmax= 8.1e-03 nm, Epot= -2.00061e+05 Fmax= 8.55983e+03, atom= 1112
Step=  337, Dmax= 9.8e-03 nm, Epot= -2.00085e+05 Fmax= 9.27435e+03, atom= 1112
Step=  339, Dmax= 5.9e-03 nm, Epot= -2.00152e+05 Fmax= 1.44616e+03, atom= 1112
Step=  340, Dmax= 7.0e-03 nm, Epot= -2.00212e+05 Fmax= 1.13365e+04, atom= 1112
Step=  341, Dmax= 8.4e-03 nm, Epot= -2.00297e+05 Fmax= 4.09463e+03, atom= 1112
Step=  343, Dmax= 5.1e-03 nm, Epot= -2.00325e+05 Fmax= 5.14117e+03, atom= 1112
Step=  344, Dmax= 6.1e-03 nm, Epot= -2.00351e+05 Fmax= 5.97181e+03, atom= 1112
Step=  345, Dmax= 7.3e-03 nm, Epot= -2.00374e+05 Fmax= 7.33683e+03, atom= 1112
Step=  346, Dmax= 8.8e-03 nm, Epot= -2.00393e+05 Fmax= 8.65779e+03, atom= 1112
Step=  347, Dmax= 1.1e-02 nm, Epot= -2.00405e+05 Fmax= 1.05167e+04, atom= 1112
Step=  348, Dmax= 1.3e-02 nm, Epot= -2.00410e+05 Fmax= 1.25071e+04, atom= 1112
Step=  350, Dmax= 7.6e-03 nm, Epot= -2.00516e+05 Fmax= 1.28802e+03, atom= 1112
Step=  351, Dmax= 9.1e-03 nm, Epot= -2.00565e+05 Fmax= 1.53711e+04, atom= 1112
Step=  352, Dmax= 1.1e-02 nm, Epot= -2.00708e+05 Fmax= 4.50471e+03, atom= 1112
Step=  354, Dmax= 6.5e-03 nm, Epot= -2.00725e+05 Fmax= 7.43788e+03, atom= 1112
Step=  355, Dmax= 7.8e-03 nm, Epot= -2.00756e+05 Fmax= 6.87211e+03, atom= 1112
Step=  356, Dmax= 9.4e-03 nm, Epot= -2.00757e+05 Fmax= 1.03181e+04, atom= 1112
Step=  357, Dmax= 1.1e-02 nm, Epot= -2.00785e+05 Fmax= 1.02957e+04, atom= 1112
Step=  359, Dmax= 6.8e-03 nm, Epot= -2.00860e+05 Fmax= 2.08984e+03, atom= 1112
Step=  360, Dmax= 8.1e-03 nm, Epot= -2.00868e+05 Fmax= 1.27179e+04, atom= 1112
Step=  361, Dmax= 9.8e-03 nm, Epot= -2.00964e+05 Fmax= 5.11101e+03, atom= 1112
Step=  363, Dmax= 5.9e-03 nm, Epot= -2.00990e+05 Fmax= 5.56593e+03, atom= 1112
Step=  364, Dmax= 7.0e-03 nm, Epot= -2.01008e+05 Fmax= 7.27153e+03, atom= 1112
Step=  365, Dmax= 8.4e-03 nm, Epot= -2.01030e+05 Fmax= 8.11184e+03, atom= 1112
Step=  366, Dmax= 1.0e-02 nm, Epot= -2.01037e+05 Fmax= 1.03655e+04, atom= 1112
Step=  367, Dmax= 1.2e-02 nm, Epot= -2.01048e+05 Fmax= 1.17964e+04, atom= 1112
Step=  369, Dmax= 7.3e-03 nm, Epot= -2.01139e+05 Fmax= 1.51854e+03, atom= 1112
Step=  370, Dmax= 8.7e-03 nm, Epot= -2.01164e+05 Fmax= 1.43786e+04, atom= 1112
Step=  371, Dmax= 1.0e-02 nm, Epot= -2.01284e+05 Fmax= 4.78715e+03, atom= 1112
Step=  373, Dmax= 6.3e-03 nm, Epot= -2.01303e+05 Fmax= 6.69284e+03, atom= 1112
Step=  374, Dmax= 7.6e-03 nm, Epot= -2.01326e+05 Fmax= 7.10362e+03, atom= 1112
Step=  375, Dmax= 9.1e-03 nm, Epot= -2.01335e+05 Fmax= 9.43611e+03, atom= 1112
Step=  376, Dmax= 1.1e-02 nm, Epot= -2.01351e+05 Fmax= 1.04243e+04, atom= 1112
Step=  378, Dmax= 6.5e-03 nm, Epot= -2.01424e+05 Fmax= 1.47685e+03, atom= 1112
Step=  379, Dmax= 7.8e-03 nm, Epot= -2.01458e+05 Fmax= 1.28659e+04, atom= 1112
Step=  380, Dmax= 9.4e-03 nm, Epot= -2.01555e+05 Fmax= 4.27900e+03, atom= 1112
Step=  382, Dmax= 5.6e-03 nm, Epot= -2.01576e+05 Fmax= 6.02291e+03, atom= 1112
Step=  383, Dmax= 6.8e-03 nm, Epot= -2.01599e+05 Fmax= 6.32063e+03, atom= 1112
Step=  384, Dmax= 8.1e-03 nm, Epot= -2.01610e+05 Fmax= 8.50733e+03, atom= 1112
Step=  385, Dmax= 9.7e-03 nm, Epot= -2.01629e+05 Fmax= 9.27422e+03, atom= 1112
Step=  387, Dmax= 5.8e-03 nm, Epot= -2.01689e+05 Fmax= 1.40879e+03, atom= 1112
Step=  388, Dmax= 7.0e-03 nm, Epot= -2.01731e+05 Fmax= 1.13528e+04, atom= 1112
Step=  389, Dmax= 8.4e-03 nm, Epot= -2.01808e+05 Fmax= 4.02504e+03, atom= 1112
Step=  391, Dmax= 5.1e-03 nm, Epot= -2.01830e+05 Fmax= 5.18612e+03, atom= 1112
Step=  392, Dmax= 6.1e-03 nm, Epot= -2.01852e+05 Fmax= 5.88572e+03, atom= 1112
Step=  393, Dmax= 7.3e-03 nm, Epot= -2.01868e+05 Fmax= 7.38497e+03, atom= 1112
Step=  394, Dmax= 8.7e-03 nm, Epot= -2.01884e+05 Fmax= 8.55288e+03, atom= 1112
Step=  395, Dmax= 1.0e-02 nm, Epot= -2.01890e+05 Fmax= 1.05647e+04, atom= 1112
Step=  396, Dmax= 1.3e-02 nm, Epot= -2.01893e+05 Fmax= 1.23794e+04, atom= 1112
Step=  398, Dmax= 7.5e-03 nm, Epot= -2.01987e+05 Fmax= 1.37359e+03, atom= 1112
Step=  399, Dmax= 9.0e-03 nm, Epot= -2.02005e+05 Fmax= 1.51975e+04, atom= 1112
Step=  400, Dmax= 1.1e-02 nm, Epot= -2.02133e+05 Fmax= 4.61664e+03, atom= 1112
Step=  402, Dmax= 6.5e-03 nm, Epot= -2.02146e+05 Fmax= 7.28153e+03, atom= 1112
Step=  403, Dmax= 7.8e-03 nm, Epot= -2.02170e+05 Fmax= 6.98621e+03, atom= 1112
Step=  405, Dmax= 4.7e-03 nm, Epot= -2.02209e+05 Fmax= 1.58503e+03, atom= 1112
Step=  406, Dmax= 5.6e-03 nm, Epot= -2.02244e+05 Fmax= 8.66724e+03, atom= 1112
Step=  407, Dmax= 6.8e-03 nm, Epot= -2.02293e+05 Fmax= 3.67174e+03, atom= 1112
Step=  409, Dmax= 4.1e-03 nm, Epot= -2.02315e+05 Fmax= 3.71955e+03, atom= 1112
Step=  410, Dmax= 4.9e-03 nm, Epot= -2.02335e+05 Fmax= 5.16585e+03, atom= 1112
Step=  411, Dmax= 5.8e-03 nm, Epot= -2.02356e+05 Fmax= 5.48245e+03, atom= 1112
Step=  412, Dmax= 7.0e-03 nm, Epot= -2.02370e+05 Fmax= 7.30744e+03, atom= 1112
Step=  413, Dmax= 8.4e-03 nm, Epot= -2.02387e+05 Fmax= 8.03142e+03, atom= 1112
Step=  414, Dmax= 1.0e-02 nm, Epot= -2.02389e+05 Fmax= 1.03805e+04, atom= 1112
Step=  415, Dmax= 1.2e-02 nm, Epot= -2.02397e+05 Fmax= 1.17148e+04, atom= 1112
Step=  417, Dmax= 7.3e-03 nm, Epot= -2.02481e+05 Fmax= 1.55409e+03, atom= 1112
Step=  418, Dmax= 8.7e-03 nm, Epot= -2.02486e+05 Fmax= 1.43188e+04, atom= 1112
Step=  419, Dmax= 1.0e-02 nm, Epot= -2.02596e+05 Fmax= 4.78159e+03, atom= 1112
Step=  421, Dmax= 6.3e-03 nm, Epot= -2.02611e+05 Fmax= 6.66627e+03, atom= 1112
Step=  422, Dmax= 7.5e-03 nm, Epot= -2.02630e+05 Fmax= 7.08074e+03, atom= 1112
Step=  423, Dmax= 9.0e-03 nm, Epot= -2.02635e+05 Fmax= 9.41049e+03, atom= 1112
Step=  424, Dmax= 1.1e-02 nm, Epot= -2.02647e+05 Fmax= 1.03807e+04, atom= 1112
Step=  426, Dmax= 6.5e-03 nm, Epot= -2.02714e+05 Fmax= 1.48433e+03, atom= 1112
Step=  427, Dmax= 7.8e-03 nm, Epot= -2.02731e+05 Fmax= 1.27907e+04, atom= 1112
Step=  428, Dmax= 9.4e-03 nm, Epot= -2.02821e+05 Fmax= 4.30137e+03, atom= 1112
Step=  430, Dmax= 5.6e-03 nm, Epot= -2.02837e+05 Fmax= 5.96198e+03, atom= 1112
Step=  431, Dmax= 6.7e-03 nm, Epot= -2.02855e+05 Fmax= 6.34583e+03, atom= 1112
Step=  432, Dmax= 8.1e-03 nm, Epot= -2.02864e+05 Fmax= 8.42913e+03, atom= 1112
Step=  433, Dmax= 9.7e-03 nm, Epot= -2.02877e+05 Fmax= 9.29923e+03, atom= 1112
Step=  435, Dmax= 5.8e-03 nm, Epot= -2.02933e+05 Fmax= 1.34661e+03, atom= 1112
Step=  436, Dmax= 7.0e-03 nm, Epot= -2.02964e+05 Fmax= 1.13916e+04, atom= 1112
Step=  437, Dmax= 8.4e-03 nm, Epot= -2.03036e+05 Fmax= 3.93350e+03, atom= 1112
Step=  439, Dmax= 5.0e-03 nm, Epot= -2.03053e+05 Fmax= 5.25263e+03, atom= 1112
Step=  440, Dmax= 6.0e-03 nm, Epot= -2.03071e+05 Fmax= 5.77850e+03, atom= 1112
Step=  441, Dmax= 7.2e-03 nm, Epot= -2.03083e+05 Fmax= 7.45389e+03, atom= 1112
Step=  442, Dmax= 8.7e-03 nm, Epot= -2.03096e+05 Fmax= 8.42754e+03, atom= 1112
Step=  443, Dmax= 1.0e-02 nm, Epot= -2.03097e+05 Fmax= 1.06326e+04, atom= 1112
Step=  444, Dmax= 1.3e-02 nm, Epot= -2.03100e+05 Fmax= 1.22326e+04, atom= 1112
Step=  446, Dmax= 7.5e-03 nm, Epot= -2.03186e+05 Fmax= 1.47797e+03, atom= 1112
Step=  448, Dmax= 4.5e-03 nm, Epot= -2.03219e+05 Fmax= 6.77101e+03, atom= 1112
Step=  449, Dmax= 5.4e-03 nm, Epot= -2.03252e+05 Fmax= 3.10389e+03, atom= 1112
Step=  450, Dmax= 6.5e-03 nm, Epot= -2.03255e+05 Fmax= 8.75301e+03, atom= 1112
Step=  451, Dmax= 7.8e-03 nm, Epot= -2.03295e+05 Fmax= 5.46942e+03, atom= 1112
Step=  453, Dmax= 4.7e-03 nm, Epot= -2.03320e+05 Fmax= 3.07048e+03, atom= 1112
Step=  454, Dmax= 5.6e-03 nm, Epot= -2.03331e+05 Fmax= 7.16798e+03, atom= 1112
Step=  455, Dmax= 6.7e-03 nm, Epot= -2.03361e+05 Fmax= 5.12630e+03, atom= 1112
Step=  457, Dmax= 4.0e-03 nm, Epot= -2.03385e+05 Fmax= 2.24442e+03, atom= 1112
Step=  458, Dmax= 4.8e-03 nm, Epot= -2.03403e+05 Fmax= 6.60967e+03, atom= 1112
Step=  459, Dmax= 5.8e-03 nm, Epot= -2.03433e+05 Fmax= 4.00665e+03, atom= 1112
Step=  461, Dmax= 3.5e-03 nm, Epot= -2.03453e+05 Fmax= 2.36866e+03, atom= 1112
Step=  462, Dmax= 4.2e-03 nm, Epot= -2.03473e+05 Fmax= 5.27261e+03, atom= 1112
Step=  463, Dmax= 5.0e-03 nm, Epot= -2.03496e+05 Fmax= 3.90530e+03, atom= 1112
Step=  464, Dmax= 6.0e-03 nm, Epot= -2.03505e+05 Fmax= 7.10415e+03, atom= 1112
Step=  465, Dmax= 7.2e-03 nm, Epot= -2.03530e+05 Fmax= 6.10961e+03, atom= 1112
Step=  467, Dmax= 4.3e-03 nm, Epot= -2.03560e+05 Fmax= 1.81411e+03, atom= 1112
Step=  468, Dmax= 5.2e-03 nm, Epot= -2.03581e+05 Fmax= 7.70269e+03, atom= 1112
Step=  469, Dmax= 6.3e-03 nm, Epot= -2.03618e+05 Fmax= 3.70973e+03, atom= 1112
Step=  471, Dmax= 3.8e-03 nm, Epot= -2.03638e+05 Fmax= 3.14216e+03, atom= 1112
Step=  472, Dmax= 4.5e-03 nm, Epot= -2.03654e+05 Fmax= 5.07466e+03, atom= 1112
Step=  473, Dmax= 5.4e-03 nm, Epot= -2.03674e+05 Fmax= 4.78984e+03, atom= 1112
Step=  474, Dmax= 6.5e-03 nm, Epot= -2.03683e+05 Fmax= 7.04610e+03, atom= 1112
Step=  475, Dmax= 7.8e-03 nm, Epot= -2.03701e+05 Fmax= 7.15621e+03, atom= 1112
Step=  477, Dmax= 4.7e-03 nm, Epot= -2.03737e+05 Fmax= 1.36154e+03, atom= 1112
Step=  478, Dmax= 5.6e-03 nm, Epot= -2.03768e+05 Fmax= 8.86844e+03, atom= 1112
Step=  479, Dmax= 6.7e-03 nm, Epot= -2.03814e+05 Fmax= 3.39978e+03, atom= 1112
Step=  481, Dmax= 4.0e-03 nm, Epot= -2.03832e+05 Fmax= 3.96425e+03, atom= 1112
Step=  482, Dmax= 4.8e-03 nm, Epot= -2.03848e+05 Fmax= 4.86995e+03, atom= 1112
Step=  483, Dmax= 5.8e-03 nm, Epot= -2.03863e+05 Fmax= 5.73226e+03, atom= 1112
Step=  484, Dmax= 7.0e-03 nm, Epot= -2.03876e+05 Fmax= 6.99161e+03, atom= 1112
Step=  485, Dmax= 8.4e-03 nm, Epot= -2.03886e+05 Fmax= 8.27340e+03, atom= 1112
Step=  486, Dmax= 1.0e-02 nm, Epot= -2.03889e+05 Fmax= 1.00525e+04, atom= 1112
Step=  488, Dmax= 6.0e-03 nm, Epot= -2.03949e+05 Fmax= 9.48117e+02, atom= 1112

writing lowest energy coordinates.

Steepest Descents converged to Fmax < 1000 in 489 steps
Potential Energy  = -2.0394900e+05
Maximum force     =  9.4811725e+02 on atom 1112
Norm of force     =  3.5937062e+01

GROMACS reminds you: "You Got to Relate to It" (A.E. Torda)
<!-- ```{bash} -->
<!-- gmx make_ndx -h -->

<!-- ``` -->

#make ndx
```{bash}
gmx make_ndx -f lig.gro -o index_lig.ndx

```

GROMACS:      gmx make_ndx, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx make_ndx -f lig.gro -o index_lig.ndx


Reading structure file
Going to read 0 old index file(s)
Analysing residue names:
There are:     1      Other residues
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...

  0 System              :    49 atoms
  1 Other               :    49 atoms
  2 LIG                 :    49 atoms

 nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
 'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
 't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
 'r': residue              'res' nr         'chain' char
 "name": group             'case': case sensitive           'q': save and quit
 'ri': residue index

> 0 & ! a H*

Copied index group 0 'System'
Found 21 atoms with name H*
Complemented group: 28 atoms
Merged two groups with AND: 49 28 -> 28

  3 System_&_!H*        :    28 atoms

> q


GROMACS reminds you: "I went to Venice and looked at the paintings of Canaletto to understand how he presented perspective, and it turned out it was an exponential law. If I had published this, maybe there would be a Karplus law in art theory as well as the Karplus equation in NMR" (Martin Karplus, Nobel lecture 2013)

<!-- ```{bash} -->
<!-- gmx genrestr -h -->

<!-- ``` -->

#genrestr
```{bash}
gmx genrestr -f lig.gro -n index_lig.ndx -o posre_lig.itp -fc 1000 1000 1000

```

GROMACS:      gmx genrestr, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx genrestr -f lig.gro -n index_lig.ndx -o posre_lig.itp -fc 1000 1000 1000


Reading structure file
Select group to position restrain
Group     0 (         System) has    49 elements
Group     1 (          Other) has    49 elements
Group     2 (            LIG) has    49 elements
Group     3 (   System_&_!H*) has    28 elements
Select a group: 3
Selected 3: 'System_&_!H*'

GROMACS reminds you: "I Don't Like Dirt" (The Breeders)

#editing of topol.top
```{bash}
gedit topol.top

```

```
; Ligand position restraints
#ifdef POSRES_LIG
#include "posre_lig.itp"
#endif
```
#make ndx
```{bash}
gmx make_ndx -f em.gro -o index.ndx

```
GROMACS:      gmx make_ndx, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx make_ndx -f em.gro -o index.ndx


Reading structure file
Going to read 0 old index file(s)
Analysing residue names:
There are:    71    Protein residues
There are:     1      Other residues
There are:  4290      Water residues
There are:     2        Ion residues
Analysing Protein...
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...

  0 System              : 14016 atoms
  1 Protein             :  1095 atoms
  2 Protein-H           :   548 atoms
  3 C-alpha             :    71 atoms
  4 Backbone            :   213 atoms
  5 MainChain           :   283 atoms
  6 MainChain+Cb        :   346 atoms
  7 MainChain+H         :   354 atoms
  8 SideChain           :   741 atoms
  9 SideChain-H         :   265 atoms
 10 Prot-Masses         :  1095 atoms
 11 non-Protein         : 12921 atoms
 12 Other               :    49 atoms
 13 LIG                 :    49 atoms
 14 CL                  :     2 atoms
 15 Water               : 12870 atoms
 16 SOL                 : 12870 atoms
 17 non-Water           :  1146 atoms
 18 Ion                 :     2 atoms
 19 LIG                 :    49 atoms
 20 CL                  :     2 atoms
 21 Water_and_ions      : 12872 atoms

 nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
 'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
 't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
 'r': residue              'res' nr         'chain' char
 "name": group             'case': case sensitive           'q': save and quit
 'ri': residue index

> 1 | 13

Copied index group 1 'Protein'
Copied index group 13 'LIG'
Merged two groups with OR: 1095 49 -> 1144

 22 Protein_LIG         :  1144 atoms

> q


GROMACS reminds you: "Kick the Dog and You Will Die" (Magnapop)

#grompp - nvt
```{bash}
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr

```
GROMACS:      gmx grompp, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'ns_type'
Setting the LD random seed to 2027224803
Generated 105474 of the 105570 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 1
Generated 71356 of the 105570 1-4 parameter combinations
Excluding 3 bonded neighbours molecule type 'Protein_chain_G'
turning H bonds into constraints...
Excluding 3 bonded neighbours molecule type 'LIG'
turning H bonds into constraints...
Excluding 2 bonded neighbours molecule type 'SOL'
turning H bonds into constraints...
Excluding 1 bonded neighbours molecule type 'CL'
turning H bonds into constraints...
Setting gen_seed to 1787371542
Velocities were taken from a Maxwell distribution at 300 K

NOTE 1 [file topol.top, line 10400]:
  The bond in molecule-type LIG between atoms 16 O and 17 C has an
  estimated oscillational period of 1.9e-02 ps, which is less than 10 times
  the time step of 2.0e-03 ps.
  Maybe you forgot to change the constraints mdp option.

Number of degrees of freedom in T-Coupling group Protein_LIG is 2863.70
Number of degrees of freedom in T-Coupling group Water_and_ions is 25743.30
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 300 K
Calculated rlist for 1x1 atom pair-list as 1.293 nm, buffer size 0.093 nm
Set rlist, assuming 4x4 atom pair-list, to 1.221 nm, buffer size 0.021 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup

NOTE 2 [file nvt.mdp]:
  Removing center of mass motion in the presence of position restraints
  might cause artifacts. When you are using position restraints to
  equilibrate a macro-molecule, the artifacts are usually negligible.

Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 36x32x36, spacing 0.148 0.152 0.154
Estimate for the relative computational load of the PME mesh part: 0.14
This run will generate roughly 72 Mb of data

There were 2 notes

GROMACS reminds you: "It always takes longer than you think even when you take Hofstadter's Law into account." (Hofstadter's Law)

#mdrun - nvt
```{bash}
gmx mdrun -deffnm nvt

```

GROMACS:      gmx mdrun, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx mdrun -deffnm nvt

Reading file nvt.tpr, VERSION 2020.1 (single precision)
Changing nstlist from 20 to 100, rlist from 1.221 to 1.339

1 GPU selected for this run.
Mapping of GPU IDs to the 2 GPU tasks in the 1 rank on this node:
  PP:0,PME:0
PP tasks will do (non-perturbed) short-ranged interactions on the GPU
PP task will update and constrain coordinates on the CPUPME tasks will do all aspects on the GPU
Using 1 MPI thread

Non-default thread affinity set, disabling internal thread affinity

Using 8 OpenMP threads

starting mdrun 'Protein in water'
500000 steps,   1000.0 ps.

Writing final coordinates.

               Core t (s)   Wall t (s)        (%)
       Time:    17932.528     2241.566      800.0
                         37:21
                 (ns/day)    (hour/ns)
Performance:       38.545        0.623

GROMACS reminds you: "You Should Sleep Late Man, It's Much Easier On Your Constitution" (Beastie Boys)

#grompp - npt
```{bash}
gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -r nvt.gro -p topol.top -n index.ndx -o npt.tpr

```

GROMACS:      gmx grompp, version 2020.1
Executable:   /home/praveenkumarpgiindia/gromacs-2020.1/build/bin/gmx
Data prefix:  /home/praveenkumarpgiindia/gromacs-2020.1 (source tree)
Working dir:  /home/praveenkumarpgiindia/GMX-2020/Rabies_Confidential/MD_Rank_6_39_33245
Command line:
  gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -r nvt.gro -p topol.top -n index.ndx -o npt.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'ns_type'
Setting the LD random seed to 919721391
Generated 105474 of the 105570 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 1
Generated 71356 of the 105570 1-4 parameter combinations
Excluding 3 bonded neighbours molecule type 'Protein_chain_G'
turning H bonds into constraints...
Excluding 3 bonded neighbours molecule type 'LIG'
turning H bonds into constraints...
Excluding 2 bonded neighbours molecule type 'SOL'
turning H bonds into constraints...
Excluding 1 bonded neighbours molecule type 'CL'
turning H bonds into constraints...
The center of mass of the position restraint coord's is  2.702  2.403  2.753
The center of mass of the position restraint coord's is  2.702  2.403  2.753

NOTE 1 [file topol.top, line 10400]:
  The bond in molecule-type LIG between atoms 16 O and 17 C has an
  estimated oscillational period of 1.9e-02 ps, which is less than 10 times
  the time step of 2.0e-03 ps.
  Maybe you forgot to change the constraints mdp option.

Number of degrees of freedom in T-Coupling group Protein_LIG is 2863.70
Number of degrees of freedom in T-Coupling group Water_and_ions is 25743.30
Determining Verlet buffer for a tolerance of 0.005 kJ/mol/ps at 300 K
Calculated rlist for 1x1 atom pair-list as 1.293 nm, buffer size 0.093 nm
Set rlist, assuming 4x4 atom pair-list, to 1.221 nm, buffer size 0.021 nm
Note that mdrun will redetermine rlist based on the actual pair-list setup

NOTE 2 [file npt.mdp]:
  Removing center of mass motion in the presence of position restraints
  might cause artifacts. When you are using position restraints to
  equilibrate a macro-molecule, the artifacts are usually negligible.

Reading Coordinates, Velocities and Box size from old trajectory
Will read whole trajectory
Last frame         -1 time 1000.000
Using frame at t = 1000 ps
Starting time for run is 0 ps
Calculating fourier grid dimensions for X Y Z
Using a fourier grid of 36x32x36, spacing 0.148 0.152 0.154
Estimate for the relative computational load of the PME mesh part: 0.14
This run will generate roughly 72 Mb of data

There were 2 notes

GROMACS reminds you: "Fly to the Court of England and Unfold" (Macbeth, Act 3, Scene 6, William Shakespeare)

#mdrun - npt
```{bash}
gmx mdrun -deffnm npt

```

#grompp - md simulation
```{bash}
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -n index.ndx -o md_0_10.tpr

```

#mdrun md simulation
```{bash}
gmx mdrun -deffnm md_0_10
 
```

```{bash}
vmd md_0_10.gro md_0_10.xtc

```

```{bash}
gmx trjconv -s md_0_10.tpr -f md_0_10.xtc -o md_0_10_center.xtc -center -pbc mol -ur compact

```

Select group for centering 
 
Group     1 (        Protein) has  1095 elements
 
Select group for output
 
Group     0 (         System) has 14030 elements

```

```{bash}
gmx trjconv -s md_0_10.tpr -f md_0_10_center.xtc -o start.pdb -dump 0

```

Select group for output

Group     1 (        Protein) has  1095 elements

```


```{bash}
gmx trjconv -s md_0_10.tpr -f md_0_10_center.xtc -o md_0_10_fit.xtc -fit rot+trans

```

Select group for least squares fit
 
Group     4 (       Backbone) has   213 elements
 
Select group for output


Group     0 (         System) has 14030 elements

```

```{bash}
gmx make_ndx -f em.gro -n index.ndx

``` 

Reading structure file
Going to read 1 old index file(s)

> 13 & ! a H*    

Copied index group 13 'LIG'
Found 9155 atoms with name H*
Complemented group: 4875 atoms
Merged two groups with AND: 48 4875 -> 30

25 LIG_&_!H*           :    30 atoms
 
> name 25 LIG_H

> q

```


```{bash}
gmx rms -s em.tpr -f md_0_10_center.xtc -n index.ndx -tu ns -o rmsd_lig.xvg

```

Select group for least squares fit
 
Group     4 (       Backbone) has   213 elements

Selected 4: 'Backbone'
Select group for RMSD calculation

Group    25 (          LIG_H) has    30 elements

```{bash}
xmgrace ~/GMX-2020/Rabies_Confidential/MD_Rank_5_46_52058/ZINC/rmsd_lig.xvg 

```